### ISSUE TITLE
Allow instantiated models to be added to a store.

### ISSUE THREAD

**Issue by JasperStam** [CodeYellowBV/mobx-spine#18] opened 2017-03-31 09:11 UTC
Currently the store only supports model data, objects, to be added.

**Comment by SpaceK33z** [comment] 2017-03-31 20:48
Dupe of #12

**Comment by JasperStam** [comment] 2017-03-31 22:02
No it's not, in the store.add this happens:
```
 @action add(models) {
        const singular = !isArray(models);
        models = singular ? [models] : models.slice();

        const modelInstances = models.map(this._newModel.bind(this));
```

_newModel is always called, it isn't checked if the given models are instantiated or just objects

**Comment by SpaceK33z** [comment] 2017-05-08 09:22
Re-opening since @abzainuddin also requested this feature. It has a lot to do with #12, but can be seen as a separate feature.

**Comment by SpaceK33z** [comment] 2017-05-09 07:43
Interesting point brought up by Burhan, what do we do with the `store` of a model?

**Comment by SpaceK33z** [comment] 2017-11-17 14:41
This isn't a feature that is necessary very often; if you need it I recommend to use `store.models.push(model)`. This essentially bypasses mobx-spine a bit, but since adding instantiated models to a store can cause all sorts of problems I think this is fine.

**Closed by SpaceK33z** 2017-11-17 14:41 UTC
Labels: enhancement
