### ISSUE TITLE
Updating from 0.26.3 to 0.26.7 breaks backend api support

### ISSUE THREAD

**Issue by BBooijLiewes** [CodeYellowBV/mobx-spine#78] opened 2020-01-21 20:41 UTC
When updating from 0.26.3 to 0.26.7 Mobx-spine adds an additional / in front of the api url.

Specifically when using
`api.post('/FinalPartApi/', data)`
instead of 
`api.post(${config.CY_API_URL}/api/GeneralPartApi/${SpecificModelInstance}/FinalPartApi/, data)` 

where:
```
import { Model as BModel, Store as BStore, BinderApi } from 'mobx-spine';

const myApi = new BinderApi();

export class MyClassName extends BStore {
    api = myApi;

}

export const api = myApi;
```

and

```
import {api} from './JsFileAbove';

export class Device extends MyClassName {

    doSomething(data){
        `api.post('/FinalPartApi/', data)`
    }
}
```

This transforms  E.g.: 
`/api/GeneralPartApi/{SpecificModelInstance}/FinalPartApi`
into
`//api/GeneralPartApi/{SpecificModelInstance}/FinalPartApi`

This breaks binder, since this double slash at the start of the url is not expected is not expected.
Currently this is blocking a project update, since 0.26.7 is needed for new functionality but can not be used due to above mentioned bug.

**Comment by sjamaan** [comment] 2020-01-22 11:18
Can you verify that 473aac408e07d1d1ce617c28e53599f847ae39fb tests what you're trying to do? I can't reproduce the breakage in that, so I'd appreciate if you could tweak the test to match your use case and have it break.

**Comment by BBooijLiewes** [comment] 2020-01-22 15:10
See the commit above [ a638fcf](https://github.com/CodeYellowBV/mobx-spine/commit/a638fcfc414512439fab28e299a9e6bbbcdaacae), Currently it is fixed by doing better `api.Baseurl` creation in the react-native application.
But it is still weird that while not touching the react-native app itself the entire API URL creation breaks, and no devices could communicate with the back-end correctly anymore.

Note that after talking with colleagues it could also be a weird axios edge-case/functionality that got altered, and that mobx-spine updated axios which broke the API.

**Comment by sjamaan** [comment] 2020-01-22 15:17
That's a PEBKAC issue; example.com/foo is indistinguishable from api/foo; both are relative URLs (because, think about it, you could have `http://example.org/foo/bar/example.com/qux/mooh` and it would be equally valid, and when resolving `qux/mooh` relatively to the base URL `http://example.org/foo/bar/example.com` you want the same result as when resolving `example.com/qux/mooh` relatively to `http://example.org/foo/bar`). If you want to make sure it's an absolute URL, you can prefix the base URL with the protocol like in `http://example.com/api`

If you don't want to hardcode the protocol, but do want to hardcode the domain in the URL, you can use what's known as a protocol-relative URL, which looks like `//example.com/api`.

**Closed by sjamaan** 2020-01-22 15:17 UTC
